apiVersion: kubeflow.org/v1beta1
kind: WorkspaceKind
metadata:
  name: jupyterlab-snapshot
spec:
  podTemplate:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
    culling:
      activityProbe:
        jupyter:
          lastActivity: true
      enabled: true
      maxInactiveSeconds: 86400
    extraEnv:
    - name: NB_PREFIX
      value: '{{ httpPathPrefix "jupyterlab" }}'
    extraVolumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /etc/jupyter/jupyter_server_config.d/
      name: jupyter-ipc-config
    extraVolumes:
    - emptyDir:
        medium: Memory
      name: dshm
    - name: jupyter-ipc-config
      configMap:
        name: jupyter-ipc-config
    options:
      imageConfig:
        spawner:
          default: jupyter-scipy:v1.10.0
        values:
        - id: jupyter-scipy:v1.8.0
          redirect:
            message:
              level: Info
              text: 'This update does not introduce any breaking changes in Python
                packages from SciPy. However, the version of JupyterLab has been updated
                from 3.6.6 to 4.2.5.

                '
            to: jupyter-scipy:v1.9.2
          spawner:
            description: JupyterLab, with SciPy Packages
            displayName: jupyter-scipy:v1.8.0
            hidden: true
            labels:
            - key: python_version
              value: 3.11.6
          spec:
            image: ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-scipy:v1.8.0
            imagePullPolicy: IfNotPresent
            ports:
            - id: jupyterlab
              port: 8888
        - id: jupyter-scipy:v1.9.2
          redirect:
            message:
              level: Info
              text: 'This update does not introduce any breaking changes in Python
                packages from SciPy.

                '
            to: jupyter-scipy:v1.10.0
          spawner:
            description: JupyterLab, with SciPy Packages
            displayName: jupyter-scipy:v1.9.2
            labels:
            - key: python_version
              value: 3.11.10
          spec:
            image: ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-scipy:v1.9.2
            imagePullPolicy: IfNotPresent
            ports:
            - id: jupyterlab
              port: 8888
        - id: jupyter-scipy:v1.10.0
          spawner:
            description: JupyterLab, with SciPy Packages
            displayName: jupyter-scipy:v1.10.0
            labels:
            - key: python_version
              value: 3.11.11
          spec:
            image: ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-scipy:v1.10.0
            imagePullPolicy: IfNotPresent
            ports:
            - id: jupyterlab
              port: 8888
        - id: jupyter-pytorch-cuda-full:v1.9.2
          redirect:
            message:
              level: Warning
              text: 'This update changes the version of PyTorch from 2.3.1 to 2.5.1.
                This only breaking change in a common python package is xgboost, which
                updated from 1.7.6 to 2.1.4.

                '
            to: jupyter-pytorch-cuda-full:v1.10.0
          spawner:
            description: JupyterLab, with PyTorch (CUDA), and Common Python Packages
            displayName: jupyter-pytorch-cuda-full:v1.9.2
            labels:
            - key: python_version
              value: 3.11.10
            - key: pytorch_version
              value: 2.3.1
            - key: cuda_version
              value: '12.1'
            - key: nccl_version
              value: 2.20.5
          spec:
            image: ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-pytorch-cuda-full:v1.9.2
            imagePullPolicy: IfNotPresent
            ports:
            - id: jupyterlab
              port: 8888
        - id: jupyter-pytorch-cuda-full:v1.10.0
          spawner:
            description: JupyterLab, with PyTorch (CUDA), and Common Python Packages
            displayName: jupyter-pytorch-cuda-full:v1.10.0
            labels:
            - key: python_version
              value: 3.11.11
            - key: pytorch_version
              value: 2.5.1
            - key: cuda_version
              value: '12.4'
            - key: nccl_version
              value: 2.21.5
          spec:
            image: ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-pytorch-cuda-full:v1.10.0
            imagePullPolicy: IfNotPresent
            ports:
            - id: jupyterlab
              port: 8888
      podConfig:
        spawner:
          default: tiny_cpu
        values:
        - id: tiny_cpu
          spawner:
            description: Pod with 0.1 CPU, 128 Mb RAM
            displayName: Tiny CPU
            labels:
            - key: cpu
              value: 100m
            - key: memory
              value: 128Mi
          spec:
            affinity: {}
            nodeSelector: {}
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
            tolerations: []
        - id: small_cpu
          spawner:
            description: Pod with 1 CPU, 2 GB RAM
            displayName: Small CPU
            labels:
            - key: cpu
              value: 1000m
            - key: memory
              value: 2Gi
          spec:
            resources:
              requests:
                cpu: 1000m
                memory: 2Gi
        - id: big_gpu
          spawner:
            description: Pod with 4 CPU, 16 GB RAM, and 1 GPU
            displayName: Big GPU
            labels:
            - key: cpu
              value: 4000m
            - key: memory
              value: 16Gi
            - key: gpu
              value: '1'
          spec:
            affinity: {}
            nodeSelector: {}
            resources:
              limits:
                nvidia.com/gpu: 1
              requests:
                cpu: 4000m
                memory: 16Gi
            tolerations:
            - effect: NoSchedule
              key: nvidia.com/gpu
              operator: Exists
    podMetadata:
      annotations:
        my-workspace-kind-annotation: my-value
      labels:
        my-workspace-kind-label: my-value
    podSnapshot:
      enabled: true
      storageConfigName: kubeflow-pod-snapshot-storage-config
    ports:
    - defaultDisplayName: JupyterLab
      httpProxy:
        removePathPrefix: false
        requestHeaders: {}
      id: jupyterlab
      protocol: HTTP
    probes: null
    securityContext:
      fsGroup: 100
    serviceAccount:
      name: default-editor
    volumeMounts:
      home: /home/jovyan
  spawner:
    deprecated: false
    description: A Workspace which runs JupyterLab in a Pod
    displayName: JupyterLab Notebook with PodSnapshot
    hidden: false
    icon:
      url: https://jupyter.org/assets/favicons/apple-touch-icon-152x152.png
    logo:
      url: https://upload.wikimedia.org/wikipedia/commons/3/38/Jupyter_logo.svg
