apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-home-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo
