apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow-workspaces
resources:
  - ../../../workspaces/controller/manifests/kustomize/base
  - ../../../workspaces/backend/manifests/kustomize/base
  - ../../../workspaces/frontend/manifests/kustomize/base
components:
  - ../../../workspaces/controller/manifests/kustomize/components/certmanager
patches:
  - target:
      kind: Deployment
      name: workspaces-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
        value: /health
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
        value: /health
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: kubeflow-workspaces/workspaces-serving-cert
  - target:
      kind: Certificate
      name: workspaces-serving-cert
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - workspaces-webhook-service.kubeflow-workspaces.svc
          - workspaces-webhook-service.kubeflow-workspaces.svc.cluster.local
  - target:
      kind: ValidatingWebhookConfiguration
    patch: |-
      apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      metadata:
        name: ignored
        annotations:
          cert-manager.io/inject-ca-from: kubeflow-workspaces/workspaces-serving-cert
  - target:
      kind: Deployment
      name: workspaces-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: workspaces-controller
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: USE_ISTIO
                    value: "false"
  - target:
      kind: Deployment
      name: workspaces-backend
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: workspaces-backend
      spec:
        template:
          spec:
            containers:
              - name: workspaces-backend
                env:
                  - name: DISABLE_AUTH
                    value: "false"
                  - name: USERID_HEADER
                    value: kubeflow-userid
                  - name: USERID_PREFIX
                    value: ""
                  - name: GROUPS_HEADER
                    value: kubeflow-groups
                  - name: PROXY_URL_PREFIX
                    value: /workspaces
