#
# Fast Layer Dockerfile for Custom Kubeflow JupyterLab Image (TPU)
# Extends upstream ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-scipy:v1.11.0
#

ARG BASE_IMG=ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-scipy:v1.11.0
FROM $BASE_IMG

ARG TARGETARCH=amd64

USER $NB_UID

# Install additional Python requirements for TPU (including jax[tpu], libtpu, kubeflow[spark], google-cloud-storage)
COPY --chown=${NB_USER}:${NB_GID} requirements-tpu.txt /tmp/requirements.txt
RUN PIP_NO_CACHE_DIR=off python3 -m pip install -r /tmp/requirements.txt --quiet --no-cache-dir \
 && rm -f /tmp/requirements.txt

# Pre-populate home with custom README and examples, and sync to $HOME_TMP for s6 01-copy-tmp-home
COPY --chown=${NB_USER}:${NB_GID} home/. ${HOME}/
COPY --chown=${NB_USER}:${NB_GID} examples/. ${HOME}/
RUN cp -p -r -T "${HOME}" "${HOME_TMP}" \
 && chmod -R g=u "${HOME_TMP}"
