apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-sandbox-kubeflow-edit
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
rules:
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes
  - sandboxes/status
  verbs:
  - '*'
- apiGroups:
  - extensions.agents.x-k8s.io
  resources:
  - sandboxclaims
  - sandboxclaims/status
  - sandboxtemplates
  - sandboxtemplates/status
  - sandboxwarmpools
  - sandboxwarmpools/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
